<?php

namespace AppBundle\Repository;

/**
 * LatestUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LatestUserRepository extends \Doctrine\ORM\EntityRepository
{
}
